---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  namespace: media-threadfin2
  releaseName: threadfin2
  repo: https://bjw-s-labs.github.io/helm-charts/
  valuesFile: values.yaml
  version: 1.5.1
commonAnnotations:
  meta.helm.sh/release-name: threadfin2
  meta.helm.sh/release-namespace: media-threadfin2
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Helm
