---
image:
  # -- image repository
  repository: fyb3roptik/threadfin
  # -- image tag
  tag: 1.2.34

strategy:
  type: Recreate

env:
  THREADFIN_PORT: 34400
  TZ: America/Toronto

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 34400

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true

    ingressClassName: nginx
    hosts:
      - host: threadfin2.sestary.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - threadfin2.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config-nas:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /home/threadfin/conf
    storageClass: truenas-iscsi-csi
  tmp:
    enabled: true
    type: emptyDir
    mountPath: /tmp/threadfin
