---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: authentik
    namespace: auth-authentik
    releaseName: authentik
    repo: https://charts.goauthentik.io
    valuesFile: values.yaml
    version: 2024.12.3

resources:
  - resources/secret.yaml

patches:
  - path: patches/secret.yaml
