---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  namespace: media-radarr
  releaseName: radarr
  repo: https://bjw-s-labs.github.io/helm-charts/
  valuesFile: values.yaml
  version: 4.0.1
commonAnnotations:
  meta.helm.sh/release-name: radarr
  meta.helm.sh/release-namespace: media-radarr

resources:
- resources/pv.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Helm
