---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  namespace: home-prusa-cameras
  releaseName: prusa-cameras
  repo: https://bjw-s-labs.github.io/helm-charts/
  valuesFile: values.yaml
  version: 4.4.0
commonAnnotations:
  meta.helm.sh/release-name: prusa-cameras
  meta.helm.sh/release-namespace: home-prusa-cameras
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Helm
