---
controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: jtee3d/prusa_connect_rtsp
          # -- image tag
          tag: latest

        env:
          CAMERA_URLS: >
            <path:secrets.enc.yaml#mini_url>,
            <path:secrets.enc.yaml#xl_url>
          TOKENS: >
            <path:secrets.enc.yaml#mini_token>,
            <path:secrets.enc.yaml#xl_token>
          CAMERA_CYCLE_DELAY: 2
