---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opnsense-telegraf
  labels:
    app.kubernetes.io/name: opnsense-telegraf 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opnsense-telegraf 
  jobLabel: opnsense-telegraf 
  endpoints:
    - port: metrics
      interval: 10s
      honorLabels: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_endpoint_node_name
          targetLabel: __address__
