---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  namespace: media-prowlarr
  releaseName: prowlarr
  repo: https://bjw-s-labs.github.io/helm-charts/
  valuesFile: values.yaml
  version: 1.5.1
commonAnnotations:
  meta.helm.sh/release-name: prowlarr
  meta.helm.sh/release-namespace: media-prowlarr
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Helm
