---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-pdc-agent
  labels:
    app: grafana-pdc-agent
    name: grafana-pdc-agent
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- with .Values.secrets }}
  cluster: {{ .cluster }}
  hosted-grafana-id: {{ .hosted_grafana_id}}
  token: {{ .token }}
  {{- end -}}
