---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  namespace: media-tautulli
  releaseName: tautulli
  repo: https://bjw-s-labs.github.io/helm-charts/
  valuesFile: values.yaml
  version: 4.3.0
commonAnnotations:
  meta.helm.sh/release-name: tautulli
  meta.helm.sh/release-namespace: media-tautulli
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Helm
