---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: prometheus-ipmi-exporter
  namespace: monitoring-ipmi-exporter
  releaseName: ipmi-exporter
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.yaml
  version: 0.6.2

commonAnnotations:
  meta.helm.sh/release-name: ipmi-exporter
  meta.helm.sh/release-namespace: monitoring-ipmi-exporter

resources:
- resources/secret.yaml
