---
controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: filebrowser/filebrowser
          # -- image tag
          tag: v2-s6

        env:
          PUID: 1000
          PGID: 1000
          FB_PORT: 8080
          FB_NOAUTH: true
          FB_ROOT: /media
      
        ports:
          - name: http
            containerPort: 8080

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true

    annotations:
      nginx.ingress.kubernetes.io/auth-url: |-
        http://ak-outpost-sestary-outpost.auth-authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
      nginx.ingress.kubernetes.io/auth-signin: |-
        https://filebrowser.sestary.eu/outpost.goauthentik.io/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
      nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;

    className: nginx

    hosts:
      - host: filebrowser.sestary.eu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - filebrowser.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  media:
    enabled: true

    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: "-"
    volumeName: truenas-media-filebrowser

    size: 25Ti

    globalMounts:
      - path: /media

  database:
    enabled: true
    type: emptyDir

    globalMounts:
      - path: /database
