ARG IMAGE_TAG
FROM ubuntu:${IMAGE_TAG} AS downloader

# Copy the versions yaml file
COPY images/argocd-plugin/versions.yaml ./

# Create the directory
RUN mkdir /tools

# Install base tools
RUN apt-get update && apt-get install -y ca-certificates jq wget
RUN wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq

# Download the k8s tools
RUN export VERSION=$(yq ".argocd-vault-plugin" versions.yaml); wget -q https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${VERSION}/argocd-vault-plugin_${VERSION}_linux_amd64 -O /tools/argocd-vault-plugin && chmod +x /tools/argocd-vault-plugin
RUN export VERSION=$(yq ".helm" versions.yaml); wget -q https://get.helm.sh/helm-v${VERSION}-linux-amd64.tar.gz -O - | tar xpz && mv linux-amd64/helm /tools/helm && chmod +x /tools/helm
RUN export VERSION=$(yq ".kustomize" versions.yaml); wget -q https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${VERSION}/kustomize_v${VERSION}_linux_amd64.tar.gz -O - | tar xz && mv kustomize /tools/kustomize && chmod a+x /tools/kustomize

# Build a clean container
FROM ubuntu:${IMAGE_TAG}

# Copy all the files we actually want from the builder
COPY --from=downloader /usr/local/bin/yq /tools/* /usr/local/bin
COPY --from=downloader /etc/ssl /etc/ssl
