---
controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: homebridge/homebridge
          # -- image tag
          tag: 2024-12-19

        ports:
          - name: http
            containerPort: 8581

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true

    pod:
      # Needed due to the HomeKit plugin
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 8581

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    
    className: nginx

    hosts:
      - host: homebridge.sestary.eu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - homebridge.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  config-nas:
    enabled: true

    suffix: config-nas

    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: truenas-iscsi-csi

    size: 40Gi

    globalMounts:
      - path: /homebridge
