---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  namespace: media-sonarr
  releaseName: sonarr
  repo: https://bjw-s-labs.github.io/helm-charts/
  valuesFile: values.yaml
  version: 4.4.0
commonAnnotations:
  meta.helm.sh/release-name: sonarr
  meta.helm.sh/release-namespace: media-sonarr

resources:
- resources/pv.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Helm
