---
- hosts: debian
  gather_facts: false
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: robbert
      state: present
      key: "{{ lookup('file', '/Users/robbert/.ssh/id_ed25519.pub') }}"

