---
replicaCount: 1

image:
  repository: ghcr.io/unpoller/unpoller
  tag: v2.15.3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceMonitor:
  # When set true then use a ServiceMonitor to configure scraping
  enabled: true 

  # Set how frequently Prometheus should scrape
  interval: 30s
  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  # labels:
  # Set timeout for scrape
  # timeout: 10s
  # Set of labels to transfer from the Kubernetes Service onto the target
  # targetLabels: []
  # MetricRelabelConfigs to apply to samples before ingestion
  # metricRelabelings: []
  # Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
  # relabelings: []
  # HTTP scheme to use for scraping. For example `http` or `https`. Default is `http`.
  # scheme: http
  # TLS configuration to use when scraping the metric endpoint by Prometheus.
  # tlsConfig: {}

  # Define each target's endpoint and name
  # When not using sharedAuthModule the config file should have one authModule for each target with key "client.$name"
  targets: 
    - endpoint: https://unifi.sestary.eu:8443
      name: ontario

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: metrics
readinessProbe:
  httpGet:
    path: /
    port: metrics

nodeSelector: {}

tolerations: []

affinity: {}

upConfig: |
  [poller]
    debug = false
    quiet = false
    plugins = []
  [unifi]
    # This must be enabled to do dynamic polls against unconfigured urls.
    dynamic = true
  [unifi.defaults]
    user       = "unpoller"
    pass       = "<path:secrets.enc.yaml#unifi_password>"
    sites      = ["all"]
    save_ids   = false
    save_dpi   = false
    save_sites = true
    verify_ssl = false
