{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unpoller.fullname" . }}
  labels:
    {{- include "unpoller.labels" . | nindent 4 }}
spec:
  endpoints:
  {{- range  .Values.serviceMonitor.targets }}
    - path: /scrape
      port: metrics 
  {{- if $.Values.serviceMonitor.interval }}
      interval: {{ $.Values.serviceMonitor.interval }}
  {{- end }}
  {{- if $.Values.serviceMonitor.timeout }}
      scrapeTimeout: {{ $.Values.serviceMonitor.timeout }}
  {{- end }}
  {{- if $.Values.serviceMonitor.scheme }}
      scheme: {{ $.Values.serviceMonitor.scheme }}
  {{- end }}
  {{- with $.Values.serviceMonitor.tlsConfig }}
      tlsConfig:
  {{- toYaml . | nindent 6 }}
  {{- end }}
      metricRelabelings:
        - action: replace
          replacement: {{ .endpoint }}
          sourceLabels: [instance]
          targetLabel: instance
        - action: replace
          replacement: {{ .name }}
          sourceLabels: [target]
          targetLabel: target
      {{- if $.Values.serviceMonitor.metricRelabelings -}}
        {{ toYaml $.Values.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
  {{- if $.Values.serviceMonitor.relabelings }}
      relabelings: {{ toYaml $.Values.serviceMonitor.relabelings | nindent 8 }}
  {{- end }}
      params:
        target:
          - {{ .endpoint }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unpoller.selectorLabels" . | nindent 6 }}
  jobLabel: {{ include "unpoller.fullname" . }}
{{- end }}

