---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app-template
  namespace: media-threadfin
  releaseName: threadfin
  repo: https://bjw-s-labs.github.io/helm-charts/
  valuesFile: values.yaml
  version: 4.0.1
commonAnnotations:
  meta.helm.sh/release-name: threadfin
  meta.helm.sh/release-namespace: media-threadfin
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Helm
