---
controllers:
  threadfin:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: fyb3roptik/threadfin
          # -- image tag
          tag: 1.2.35

        env:
          THREADFIN_PORT: 34400
          TZ: America/Toronto

  threadfin2:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: fyb3roptik/threadfin
          # -- image tag
          tag: 1.2.35

        env:
          THREADFIN_PORT: 34400
          TZ: America/Toronto

# -- Configures service settings for the chart.
service:
  threadfin:
    controller: threadfin
    ports:
      http:
        port: 34400

  threadfin2:
    controller: threadfin2
    ports:
      http:
        port: 34400

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  threadfin:
    enabled: true

    className: nginx

    hosts:
      - host: threadfin.sestary.eu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: threadfin
              port: http
      
      - host: threadfin2.sestary.eu
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: threadfin2
              port: http

    tls:
      - hosts:
          - threadfin.sestary.eu
          - threadfin2.sestary.eu

# -- Configure persistence settings for the chart under this key.
persistence:
  threadfin-nas:
    enabled: true
   
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: truenas-iscsi-csi

    size: 10Gi

    advancedMounts:
      threadfin:
        main:
          - path: /home/threadfin/conf

  threadfin2-nas:
    enabled: true
   
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: truenas-iscsi-csi

    size: 10Gi

    advancedMounts:
      threadfin2:
        main:
          - path: /home/threadfin/conf


  tmp:
    enabled: true
    type: emptyDir

    globalMounts:
      - path: /tmp/threadfin
