---
name: Build container images
on:
  push:
    branches:
      - main
    paths:
      - images/**
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # every monday at midnight
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - argocd-plugin
          - authentik
          - terraform-cloud-agent

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v5

      # Read the tag from the YAML file
      - name: Get image tag
        id: image_tag
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: images/${{ matrix.image }}/versions.yaml

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image }}
          tags: ${{ steps.image_tag.outputs['image_tag'] }} ${{ github.sha }}
          build-args:
            IMAGE_TAG=${{ steps.image_tag.outputs['image_tag'] }}
          containerfiles: |
            images/${{ matrix.image }}/Containerfile

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        id: push_ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push_ghcr.outputs) }}"
